swagger: "2.0"

info:
  title: "{{title}}"
  version: "1.0"

paths:
  /greeting:
    post:
      summary: Generate greeting
      description: Generates a greeting message.
      operationId: app.post_greeting
      produces:
        - application/json
      responses:
        200:
          description: greeting response
          schema:
            type: string
      parameters:
        - in: body
          name: pubsub_message
          description: Pubsub message
          schema:
            type: object
            properties:
              foo:
                type: string
            # type: object
            # properties:
            #   message:
            #     type: object
            #     properties:
            #       attributes:
            #         type: object
            #       data:
            #         type: string
            #         example: "SGVsbG8gQ2xvdWQgUHViL1N1YiEgSGVyZSBpcyBteSBtZXNzYWdlIQ=="
            #   subscription:
            #     type: string
